plugins {
    id 'application'
    id 'org.jetbrains.kotlin.jvm' version '2.1.10'
    id "io.freefair.lombok" version "8.12.2"
}

group = 'razesoldier'
version = '1.12.0'

repositories {
    mavenCentral()
}

dependencies {
    api('top.mrxiaom.mirai:overflow-core:1.0.7')
    runtimeOnly("top.mrxiaom.mirai:overflow-core:1.0.7")
    implementation('com.alibaba.fastjson2:fastjson2:2.0.56')
    api('org.slf4j:slf4j-api:2.0.16')
    runtimeOnly('org.slf4j:slf4j-simple:2.0.16')
    implementation('com.github.mizosoft.methanol:methanol:1.8.1') // https://github.com/mizosoft/methanol/
    implementation('com.google.guava:guava:33.4.0-jre') // https://github.com/google/guava
    implementation('com.google.inject:guice:7.0.0')
    implementation('com.google.inject.extensions:guice-throwingproviders:7.0.0')
    implementation('org.jsoup:jsoup:1.18.3')
    implementation('com.discord4j:discord4j-core:3.2.8')
    implementation('com.tencentcloudapi:tencentcloud-sdk-java-tmt:3.1.1297')
    implementation("org.atteo:evo-inflector:1.3")
    testImplementation('org.junit.jupiter:junit-jupiter:5.12.0')
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'razesoldier.gdlbot.Entry'
    applicationDefaultJvmArgs = ['-Dmirai.no-desktop', '-Xmx128m']
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(23)
    }
}

jar {
    manifest.attributes = ["Manifest-Version": archiveVersion, 'Main-Class': 'razesoldier.gdlbot.Entry']
}

test {
    useJUnitPlatform()
}